[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4

[[main]]
    identifier = "Posts"
    name = "Donate"
    url = "/posts"
    weight = 5
    
# Social Media Configuration


[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "#"
    weight = 1

